### ISSUE TITLE
generate_data.py运行报错

### ISSUE THREAD

**Issue by Wandypt** [Rachelxuan11/FLAME#1]
traceback like this:
python generate_data.py                                                     
[6903, 7877, 6990, 7141, 6824, 6313, 6876, 7293, 6825, 6958]
Assign samples to each user
Traceback (most recent call last):
  File "/Users/aaaa/miniconda3/envs/FLAME-master/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "generate_data.py", line 47, in <module>
    X[user].append(mnist_data[l][idx[l]].tolist())
  File "/Users/aaa/miniconda3/envs/FLAME-master/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/aaa/miniconda3/envs/FLAME-master/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 0
最近在做混洗模型的差分隐私联邦学习，想先学习下前辈的模型，运行时发生了问题，数据集处理时报错，能帮忙看看这是为什么嘛

**Comment by Swgj** [comment]
@aspfy，你好，我也遇到了你一样的问题，请问你是怎么解决的呢？

**Comment by Swgj** [comment]
D:\Anaconda3\envs\ShuffleFL\python.exe D:/Codes/python/differential_privacy/FLAME/generate_data.py
[6903, 7877, 6990, 7141, 6824, 6313, 6876, 7293, 6825, 6958]
Assign samples to each user
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Codes/python/differential_privacy/FLAME/generate_data.py", line 47, in <module>
    X[user].append(mnist_data[l][idx[l]].tolist())
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 0

Process finished with exit code 1

**Comment by Wandypt** [comment]
换了个服务器可以跑，我在google的那个colab可以运行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Swgj ***@***.***&gt;
发送时间: 2022年3月5日 10:00
收件人: Rachelxuan11/FLAME ***@***.***&gt;
抄送: aspfcy ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Rachelxuan11/FLAME] generate_data.py运行报错 (#1)






@aspfy，你好，我也遇到了你一样的问题，请问你是怎么解决的呢？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Swgj** [comment]
刚刚尝试了google的colab，结果得到了和你问题描述中一模一样的错误😖，请问方便的话能否将这个程序划分好的test和train训练集发一下呢？如果可以的话，不胜感激🌹 
![image](https://user-images.githubusercontent.com/68093687/156866376-191bebd7-6587-49d0-bf73-be7959df0225.png)

**Comment by Swgj** [comment]
换了一个操作系统，问题就都解决了。orz

**Comment by TigerAB1** [comment]
@Wandypt 前辈我能请教您一个问题吗？
![image](https://github.com/Rachelxuan11/FLAME/assets/116572728/66490679-d8a9-45e6-b40e-38b5a23c3722)
为什么这里面要除以em_s啊
