### ISSUE TITLE
generate_data.py运行报错

### ISSUE THREAD

**Issue by Swgj** [Rachelxuan11/FLAME#3]
前辈您好，最近我在阅读您的这篇论文，在代码复现的过程中这个地方一直报错，请问有没有什么好的解决办法？或者请问能否将数据文件上传共享？
D:\Anaconda3\envs\ShuffleFL\python.exe D:/Codes/python/differential_privacy/FLAME/generate_data.py
[6903, 7877, 6990, 7141, 6824, 6313, 6876, 7293, 6825, 6958]
Assign samples to each user
Traceback (most recent call last):
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\indexes\base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/Codes/python/differential_privacy/FLAME/generate_data.py", line 47, in <module>
    X[user].append(mnist_data[l][idx[l]].tolist())
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "D:\Anaconda3\envs\ShuffleFL\lib\site-packages\pandas\core\indexes\base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 0

Process finished with exit code 1

**Comment by Swgj** [comment]
换了一个操作系统，问题就都解决了

**Comment by TigerAB1** [comment]
@Swgj 您好，换了一个什么操作系统啊？

**Comment by Swgj** [comment]
> @Swgj 您好，换了一个什么操作系统啊？

Linux系统应该都行，我当时用的Ubuntu

**Comment by TigerAB1** [comment]
> > @Swgj 您好，换了一个什么操作系统啊？
> 
> Linux系统应该都行，我当时用的Ubuntu

好的，感谢

**Comment by TigerAB1** [comment]
@Swgj 前辈我能在请教您一个问题吗？就是他这个代码中
![image](https://github.com/Rachelxuan11/FLAME/assets/116572728/6aaba70e-f24b-46fe-96c6-bed86baeacf1)
这个为什么除的是em_s
